[workspace]
resolver = "2" 
members = [
   "./crates/bomber_game",
   "./crates/bomber_lib",
   "./crates/bomber_macro",
   "./crates/bomber_plugins/wanderer",
   "./crates/bomber_plugins/fool",
   "./crates/upload_server",
]
